# Generated by Django 5.1 on 2024-09-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contact_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='contactEnquiry',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
